Repository ros2/rcutils, pull requests merged in 2018-06, with the labels that each got.

#104 Fix a memory check issue in split.c
  src/split.c
Labels: in review

#105 migrate launch -> launch.legacy
  test/test_logging_long_messages.py
  test/test_logging_output_format.py
Labels: in review

#106 Prevent default logger's level from being unset
  include/rcutils/logging.h
  src/logging.c
  test/test_logging.cpp
Labels: in review

#101 update to use new memory_tools from osrf_testing_tools_cpp
  CMakeLists.txt
  package.xml
  test/memory_tools/CMakeLists.txt
  test/memory_tools/memory_tools.cpp
  test/memory_tools/memory_tools.hpp
  test/memory_tools/memory_tools_common.cpp
  test/memory_tools/memory_tools_osx_interpose.cpp
  test/memory_tools/scope_exit.hpp
  test/memory_tools/test_memory_tools.cpp
  test/test_allocator.cpp
  test/test_logging_macros.c
  test/test_time.cpp
Labels: enhancement, in review

#107 Parse log level from string
  include/rcutils/logging.h
  include/rcutils/types/rcutils_ret.h
  src/logging.c
  test/test_logging.cpp
Labels: in review

#85 take a timestamp when a console logging message happens
  CMakeLists.txt
  include/rcutils/logging.h
  include/rcutils/snprintf.h
  include/rcutils/time.h
  src/format_string.c
  src/logging.c
  src/snprintf.c
  src/time.c
  test/test_logging.cpp
  test/test_logging_macros.c
  test/test_logging_macros.cpp
  test/test_logging_output_format.py
  test/test_logging_output_timestamps.regex
  test/test_snprintf.cpp
  test/test_time.cpp
Labels: enhancement, in progress

#102 Dynamic memory audit
  CMakeLists.txt
  include/rcutils/allocator.h
  include/rcutils/concat.h
  include/rcutils/filesystem.h
  src/concat.c
  src/filesystem.c
  test/test_concat.cpp
  test/test_filesystem.cpp
  test/test_logging_macros.c
Labels: enhancement, in review

#108 Remove redundant stat() call.
  src/filesystem.c
Labels: in review
