Repository ros2/rcutils, pull requests merged in 2018-03, with the labels that each got.

#93 update style
  test/memory_tools/test_memory_tools.cpp
Labels: in review

#95 honor BUILD_SHARED_LIBS in test libraries as well
  test/memory_tools/CMakeLists.txt
Labels: in progress

#96 include format_string.h in error_handling.h
  include/rcutils/error_handling.h
Labels: in review

#97 make log location parameter const
  include/rcutils/logging.h
  src/logging.c
  test/test_logging.cpp
  test/test_logging_macros.c
  test/test_logging_macros.cpp
Labels: enhancement, in review

#99 fix typo
  include/rcutils/logging.h
Labels: in review

#94 Control shared/static linking via BUILD_SHARED_LIBS
  CMakeLists.txt
  package.xml
  test/memory_tools/CMakeLists.txt
Labels: in review

#98 PR for issue#70
  src/logging.c
Labels: in review
