Repository ros2/rcutils, pull requests merged in 2019-04, with the labels that each got.

#145 Windows messages when atomic type is unsupported
  include/rcutils/stdatomic_helper/win32/stdatomic.h
Labels: in review

#150 add tests for stdatomic_helper.h and fix bugs
  CMakeLists.txt
  include/rcutils/stdatomic_helper.h
  include/rcutils/stdatomic_helper/win32/stdatomic.h
  test/test_atomics.c
Labels: in review

#147 Fix ASAN failure in test_string_map.cpp
  CMakeLists.txt
  test/test_string_map.cpp
Labels: in progress

#149 Fix a leak in test_array_list.cpp
  test/test_array_list.cpp
Labels: in review

#151 Fix remaining leaks in test_string_map.cpp
  test/test_string_map.cpp
Labels: in review

#152 Fix leak in test_logging_macros.cpp
  test/test_logging_macros.cpp
Labels: in review

#153 Fix leak in test_logging.cpp
  CMakeLists.txt
  test/test_logging.cpp
Labels: in review

#154 Use GCC extension for printf-like functions
  include/rcutils/format_string.h
  include/rcutils/logging.h
  include/rcutils/macros.h
  include/rcutils/snprintf.h
  test/test_format_string.cpp
  test/test_logging.cpp
  test/test_logging_long_messages.cpp
Labels: enhancement, in review

#140 Migrate launch tests to new launch_testing features & API
  CMakeLists.txt
  package.xml
  test/test_logging_long_messages.py
  test/test_logging_output_format.py
Labels: in review
