Repository ros2/rcutils, pull requests merged in 2019-05, with the labels that each got.

#156 remove macros from source file
  src/time.c
Labels: bug, in review

#155 Add in utilities needed for log location
  CMakeLists.txt
  include/rcutils/get_env.h
  include/rcutils/process.h
  src/get_env.c
  src/process.c
Labels: in review

#157 Rename result variable for clarity.
  src/process.c
Labels: in review

#144 Add function rcutils_string_array_cmp
  include/rcutils/types/string_array.h
  src/string_array.c
  test/test_string_array.cpp
Labels: in review

#158 Add colorized output
  include/rcutils/logging.h
  src/logging.c
Labels: in review

#161 Correct bug when reading RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED
  src/logging.c
Labels: bug, in review

#160 add missing warn unused
  include/rcutils/types/string_array.h
Labels: in review

#162 getprogname() is the correct API to use on Android.
  src/process.c
Labels: bug
