Repository ros2/rcutils, pull requests merged in 2020-04, with the labels that each got.

#215 Included utils to load, unload and get symbols from shared libraries
  CMakeLists.txt
  include/rcutils/shared_library.h
  src/shared_library.c
  test/dummy_shared_library/dummy_shared_library.c
  test/dummy_shared_library/dummy_shared_library.h
  test/test_shared_library.cpp
Labels: enhancement

#222 Added rcutils_is_shared_library_loaded function
  include/rcutils/shared_library.h
  src/shared_library.c
  test/test_shared_library.cpp
Labels: enhancement

#226 Fixed condition in rcutils_get_platform_library_name
  src/shared_library.c
Labels: enhancement

#229 define NOMINMAX before including windows.h
  include/rcutils/shared_library.h
Labels: bug

#230 Assume WIN32 HINSTANCE is a void *
  include/rcutils/shared_library.h
  src/shared_library.c
Labels: bug

#236 Don't check GetLastError() on success
  src/shared_library.c
  test/test_shared_library.cpp
Labels: bug

#238 Don't assume errno is set to 0 on success on Windows
  src/snprintf.c
  test/test_snprintf.cpp
Labels: bug

#239 Set errno to EINVAL when explicitly returning -1
  src/snprintf.c
Labels: enhancement

#225 Improved documentation
  README.md
  include/rcutils/allocator.h
  include/rcutils/cmdline_parser.h
  include/rcutils/error_handling.h
  include/rcutils/filesystem.h
  include/rcutils/logging.h
  include/rcutils/macros.h
  include/rcutils/types/array_list.h
  include/rcutils/types/char_array.h
  include/rcutils/types/hash_map.h
  include/rcutils/types/uint8_array.h
  resource/logging_macros.h.em
  test/test_get_env.cpp
Labels: documentation
